const K='kenshin-made-v1',C=WeightCore;let state=load(),range='7';
const $=s=>document.querySelector(s),today=()=>new Date().toLocaleDateString('sv-SE');
function load(){try{const p=JSON.parse(localStorage.getItem(K));return C.validateBackup(p)}catch{return{version:1,records:[],settings:{goalWeight:null,goalDate:''},exportedAt:''}}}
function save(){localStorage.setItem(K,JSON.stringify({...state,exportedAt:new Date().toISOString()}));render()}
function fmt(v){return v==null?'--':`${v>0?'+':''}${v.toFixed(1)} kg`}
function render(){const d=today(),rec=state.records.find(r=>r.date===d);$('#todayLabel').textContent=new Intl.DateTimeFormat('ja-JP',{dateStyle:'full'}).format(new Date(d+'T00:00:00'));$('#weightInput').value=rec?.weight||'';$('#memoInput').value=rec?.memo||'';const diff=C.dayDiff(state.records,d);$('#dayDiff').textContent=fmt(diff);$('#dayDiffNote').textContent=diff==null?'比較できる過去記録がありません':diff===0?'前回の記録と同じです':diff<0?'前回の記録より減少':'前回の記録より増加';const wr=C.rangeRecords(state.records,7,d);$('#weekDiff').textContent=wr.length>1?fmt(C.round(wr.at(-1).weight-wr[0].weight)):'--';const latest=state.records.at(-1);$('#goalDiff').textContent=latest&&state.settings.goalWeight?`${Math.max(0,C.round(latest.weight-state.settings.goalWeight)).toFixed(1)} kg`:'--';$('#goalDateText').textContent=state.settings.goalDate?`健康診断日 ${state.settings.goalDate.replaceAll('-','/')}`:'目標を設定してください';renderRecords();drawChart()}
$('#weightForm').addEventListener('submit',e=>{e.preventDefault();const w=Number($('#weightInput').value);if(w<30||w>250){$('#formMessage').textContent='30〜250kgの範囲で入力してください';return}state.records=C.upsertRecord(state.records,{date:today(),weight:w,memo:$('#memoInput').value.trim(),updatedAt:new Date().toISOString()});$('#formMessage').textContent='今日の記録を保存しました';save()});
function renderRecords(){const box=$('#recordsList');box.innerHTML='';const list=[...state.records].reverse().slice(0,14);if(!list.length){box.innerHTML='<div class="empty">まだ記録がありません。今日の体重から始めましょう。</div>';return}list.forEach(r=>{const el=document.createElement('div');el.className='record';el.innerHTML=`<span class="date">${r.date.replaceAll('-','/')}</span><div><strong>${r.weight.toFixed(1)} kg</strong><div class="memo">${escapeHtml(r.memo)||'メモなし'}</div></div><button class="ghost edit">編集</button><button class="danger delete">削除</button>`;el.querySelector('.edit').onclick=()=>{const val=prompt(`${r.date} の体重`,r.weight);if(val===null)return;const n=Number(val);if(n>=30&&n<=250){state.records=C.upsertRecord(state.records,{...r,weight:n,updatedAt:new Date().toISOString()});save()}};el.querySelector('.delete').onclick=()=>{if(confirm(`${r.date} の記録を削除しますか？`)){state.records=state.records.filter(x=>x.date!==r.date);save()}};box.append(el)})}
function escapeHtml(v){return v.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
$('#rangeButtons').onclick=e=>{if(!e.target.dataset.range)return;range=e.target.dataset.range;document.querySelectorAll('#rangeButtons button').forEach(b=>b.classList.toggle('active',b===e.target));drawChart()};
function drawChart(){const canvas=$('#weightChart'),ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1,w=canvas.clientWidth,h=280;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const data=C.rangeRecords(state.records,range,today());if(!data.length){ctx.fillStyle='#667085';ctx.font='15px sans-serif';ctx.textAlign='center';ctx.fillText('記録するとここにグラフが表示されます',w/2,h/2);return}const vals=data.map(r=>r.weight),goal=state.settings.goalWeight;let min=Math.min(...vals,goal||Infinity)-1,max=Math.max(...vals,goal||-Infinity)+1;if(min===max){min--;max++}const L=44,R=18,T=20,B=40,x=i=>L+(data.length===1?(w-L-R)/2:i*(w-L-R)/(data.length-1)),y=v=>T+(max-v)*(h-T-B)/(max-min);ctx.strokeStyle='#dbe3ef';ctx.lineWidth=1;ctx.fillStyle='#718096';ctx.font='11px sans-serif';ctx.textAlign='right';for(let i=0;i<4;i++){const v=min+(max-min)*i/3,yy=y(v);ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(w-R,yy);ctx.stroke();ctx.fillText(v.toFixed(1),L-7,yy+4)}if(goal){ctx.setLineDash([6,5]);ctx.strokeStyle='#d97706';ctx.beginPath();ctx.moveTo(L,y(goal));ctx.lineTo(w-R,y(goal));ctx.stroke();ctx.setLineDash([])}ctx.strokeStyle='#2768d8';ctx.lineWidth=2.5;ctx.beginPath();data.forEach((r,i)=>i?ctx.lineTo(x(i),y(r.weight)):ctx.moveTo(x(i),y(r.weight)));ctx.stroke();ctx.fillStyle='#2768d8';data.forEach((r,i)=>{ctx.beginPath();ctx.arc(x(i),y(r.weight),3.5,0,Math.PI*2);ctx.fill()});ctx.strokeStyle='#1f9d74';ctx.lineWidth=2;ctx.beginPath();data.forEach((r,i)=>{const avg=C.movingAverage(data,i),xx=x(i),yy=y(avg);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke();ctx.fillStyle='#718096';ctx.textAlign='center';const step=Math.max(1,Math.ceil(data.length/6));data.forEach((r,i)=>{if(i%step===0||i===data.length-1)ctx.fillText(r.date.slice(5).replace('-','/'),x(i),h-15)})}
$('#settingsBtn').onclick=()=>{$('#goalWeightInput').value=state.settings.goalWeight||'';$('#goalDateInput').value=state.settings.goalDate||'';$('#settingsDialog').showModal()};$('#saveSettingsBtn').onclick=e=>{e.preventDefault();const g=$('#goalWeightInput').value;state.settings={goalWeight:g?Number(g):null,goalDate:$('#goalDateInput').value};save();$('#settingsDialog').close()};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kenshin-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{const data=C.validateBackup(JSON.parse(await e.target.files[0].text()));if(confirm(`${data.records.length}件の記録で現在のデータを置き換えますか？`)){state=data;save();alert('復元しました')}}catch(err){alert(err.message)}finally{e.target.value=''}};
$('#clearBtn').onclick=()=>{if(confirm('すべての体重記録と設定を削除します。元に戻せません。')){localStorage.removeItem(K);state=load();save()}};render();
